app/dashboard/views.py
from flask import Blueprint, render_template
from flask_user import roles_required
from app.tab import get_allowed_tabs
from app.auth.models import User
from app.exam.models import Exam

dashboard_blueprint = Blueprint("dashboard", __name__)


@dashboard_blueprint.route("/dashboard")
@roles_required("Admin")
def index():
    users = User.query.all()
    tabs = get_allowed_tabs()
    return render_template("dashboard/dashboard.html", tabs=tabs, users=users)


@dashboard_blueprint.route("/exam_dashboard")
@roles_required("Admin")
def list_of_exam():
    exams = (
        Exam.query.filter(Exam.deleted == False)  # noqa E712
        .filter(Exam.lang == Exam.Language.py)
        .order_by(Exam.id.desc())
        .all()
    )
    tabs = get_allowed_tabs()
    return render_template("dashboard/exam_dashboard.html", tabs=tabs, exams=exams)


@dashboard_blueprint.route("/exam_dashboard_java")
@roles_required("Admin")
def list_of_exam_java():
    exams = (
        Exam.query.filter(Exam.deleted == False)  # noqa E712
        .filter(Exam.lang == Exam.Language.java)
        .order_by(Exam.id.desc())
        .all()
    )
    tabs = get_allowed_tabs()
    return render_template("dashboard/exam_dashboard_java.html", tabs=tabs, exams=exams)


@dashboard_blueprint.route("/exam_dashboard_html")
@roles_required("Admin")
def list_of_exam_html():
    exams = (
        Exam.query.filter(Exam.deleted == False)  # noqa E712
        .filter(Exam.lang == Exam.Language.html)
        .all()
    )
    tabs = get_allowed_tabs()
    return render_template("dashboard/exam_dashboard_html.html", tabs=tabs, exams=exams)

app/result/views.py
from flask import Blueprint, render_template
from flask_user import current_user, roles_required
from app.tab import get_allowed_tabs
from app.result.models import Result
from app.auth.models import User

result_blueprint = Blueprint("result", __name__)


@result_blueprint.route("/status")
def result():
    user = User.query.filter(User.id == current_user.id).first()
    results = Result.query.filter(Result.user_id == current_user.id).all()
    tabs = get_allowed_tabs()
    return render_template("exam/status.html", tabs=tabs, results=results, user=user)


@result_blueprint.route("/status_for_admin/<user_id>")
@roles_required("Admin")
def result_for_admin(user_id):
    user_id = int(user_id)
    user = User.query.filter(User.id == user_id).first()
    results = Result.query.filter(Result.user_id == user_id).all()
    tabs = get_allowed_tabs()
    return render_template(
        "exam/status_for_admin.html", tabs=tabs, results=results, user=user
    )

app/templates/dashboard/dashboard.html
{% extends 'base.html' %}

{% block content %}
<link rel="stylesheet" href="/static/css/jquery.dataTables.min.css">
<table id="theTable" class="table table-striped table-sm" cellspacing="0" width="100%">
    <thead class="black white-text bg-secondary">
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Role</th>
            <th scope="col">Registered</th>
            <th scope="col">Active</th>
            <th scope="col">Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
            <td><a href="{{ url_for('result.result_for_admin', user_id=user.id )}}">{{user.username}}</a></td>
            <td>{% for role in user.roles %} {{ role.name }} {% endfor %}</td>
            <td>{{user.created_at}}</td>
            <td>{{user.active}}</td>
            <td><a href="{{ url_for('auth.edit_user', user_id=user.id)}}">Edit</a></td>
            <td style="text-align: center;"><a href="{{ url_for('auth.delete_user', user_id=user.id)}}"
                    class="user_delete_button btn-sm btn-outline-danger">&#10006</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<div style="margin-top: 1%;">
    <a class="btn btn-primary" href="{{ url_for('auth.register')}}">Register User</a>
    {% endblock %}
    {% block scripts %}
    <script>
        $(document).ready(function () {
            $('#theTable').DataTable();
        });
    </script>
    {% endblock %}

app/templates/dashboard/exam_dashboard.html
{% extends 'base.html' %}

{% block content %}
<link rel="stylesheet" href="/static/css/jquery.dataTables.min.css">
<div style="margin-top: 1%; margin-bottom: 1%; align-items: center;">
    <a class="btn btn-primary black white-text bg-secondary" href="{{ url_for('dashboard.list_of_exam')}}">Python</a>
    <a class="btn btn-primary black white-text bg-secondary" href="{{ url_for('dashboard.list_of_exam_java')}}">Java</a>
    <a class="btn btn-primary black white-text bg-secondary"
        href="{{ url_for('dashboard.list_of_exam_html')}}">HTML/CSS</a>
</div>
<table id="theTable" class="table table-striped table-sm" cellspacing="0" width="100%">
    <thead class="black white-text bg-secondary">
        <tr>
            <th scope="col">№</th>
            <th scope="col">Name</th>
            <th scope="col">Language</th>
            <th scope="col">Type</th>
            <th scope="col">Level</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for exam in exams %}
        <tr>
            <td>{{exam.id}}</td>
            <td><a href="{{ url_for('exam.edit_exam', exam_id=exam.id)}}">{{exam.name}}</a></td>
            <td>{{exam.lang.value}}</td>
            <td>{{exam.exam_type.name}}</td>
            <td>{{exam.exam_level.name}}</td>
            <td style="text-align: center;"><a href="{{ url_for('exam.delete_exam', exam_id=exam.id)}}"
                    class="exam_delete_button btn-sm btn-outline-danger">&#10006</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<div style="margin-top: 1%;">
    <a class="btn btn-primary" href="{{ url_for('exam.create_exam')}}">Create code questions</a>
    <a class="btn btn-primary" href="{{ url_for('exam.create_choice_exam')}}">Create multiple choice questions</a>
    {% endblock %}
    {% block scripts %}
    <script>
        $(document).ready(function () {
            $('#theTable').DataTable()({
                "order": [[0, "desc"]]
            });
        });
    </script>
    {% endblock %}

app/templates/dashboard/exam_dashboard_html.html
{% extends 'base.html' %}

{% block content %}
<link rel="stylesheet" href="/static/css/jquery.dataTables.min.css">
<div style="margin-top: 1%; margin-bottom: 1%; align-items: center;">
    <a class="btn btn-primary black white-text bg-secondary" href="{{ url_for('dashboard.list_of_exam')}}">Python</a>
    <a class="btn btn-primary black white-text bg-secondary" href="{{ url_for('dashboard.list_of_exam_java')}}">Java</a>
    <a class="btn btn-primary black white-text bg-secondary"
        href="{{ url_for('dashboard.list_of_exam_html')}}">HTML/CSS</a>
</div>
<table id="theTable" class="table table-striped table-sm" cellspacing="0" width="100%">
    <thead class="black white-text bg-secondary">
        <tr>
            <th scope="col">№</th>
            <th scope="col">Name</th>
            <th scope="col">Language</th>
            <th scope="col">Type</th>
            <th scope="col">Level</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for exam in exams %}
        <tr>
            <td>{{exam.id}}</td>
            <td><a href="{{ url_for('exam.edit_exam', exam_id=exam.id)}}">{{exam.name}}</a></td>
            <td>{{exam.lang.value}}</td>
            <td>{{exam.exam_type.name}}</td>
            <td>{{exam.exam_level.name}}</td>
            <td style="text-align: center;"><a href="{{ url_for('exam.delete_exam', exam_id=exam.id)}}"
                    class="exam_delete_button btn-sm btn-outline-danger">&#10006</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<div style="margin-top: 1%;">
    <a class="btn btn-primary" href="{{ url_for('exam.create_exam')}}">Create code questions</a>
    <a class="btn btn-primary" href="{{ url_for('exam.create_choice_exam')}}">Create multiple choice questions</a>
    {% endblock %}
    {% block scripts %}
    <script>
        $(document).ready(function () {
            $('#theTable').DataTable()({
                "order": [[0, "desc"]]
            });
        });
    </script>
    {% endblock %}

app/templates/dashboard/exam_dashboard_java.html
{% extends 'base.html' %}

{% block content %}
<link rel="stylesheet" href="/static/css/jquery.dataTables.min.css">
<div style="margin-top: 1%; margin-bottom: 1%; align-items: center;">
    <a class="btn btn-primary black white-text bg-secondary" href="{{ url_for('dashboard.list_of_exam')}}">Python</a>
    <a class="btn btn-primary black white-text bg-secondary" href="{{ url_for('dashboard.list_of_exam_java')}}">Java</a>
    <a class="btn btn-primary black white-text bg-secondary"
        href="{{ url_for('dashboard.list_of_exam_html')}}">HTML/CSS</a>
</div>
<table id="theTable" class="table table-striped table-sm" cellspacing="0" width="100%">
    <thead class="black white-text bg-secondary">
        <tr>
            <th scope="col">№</th>
            <th scope="col">Name</th>
            <th scope="col">Language</th>
            <th scope="col">Type</th>
            <th scope="col">Level</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        {% for exam in exams %}
        <tr>
            <td>{{exam.id}}</td>
            <td><a href="{{ url_for('exam.edit_exam', exam_id=exam.id)}}">{{exam.name}}</a></td>
            <td>{{exam.lang.value}}</td>
            <td>{{exam.exam_type.name}}</td>
            <td>{{exam.exam_level.name}}</td>
            <td style="text-align: center;"><a href="{{ url_for('exam.delete_exam', exam_id=exam.id)}}"
                    class="exam_delete_button btn-sm btn-outline-danger">&#10006</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<div style="margin-top: 1%;">
    <a class="btn btn-primary" href="{{ url_for('exam.create_exam')}}">Create code questions</a>
    <a class="btn btn-primary" href="{{ url_for('exam.create_choice_exam')}}">Create multiple choice questions</a>
    {% endblock %}
    {% block scripts %}
    <script>
        $(document).ready(function () {
            $('#theTable').DataTable()({
                "order": [[0, "desc"]]
            });
        });
    </script>
    {% endblock %}