app/exam/choisen_answer/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    SubmitField,
    HiddenField,
    TextAreaField,
    SelectField,
    RadioField,
)
from wtforms.validators import DataRequired, Length


class ChoiceExamForm(FlaskForm):
    exam_id = HiddenField("id")
    name = StringField("Question:")
    instruction = TextAreaField("Instruction")
    answer = RadioField("Answer")
    submit = SubmitField("Submit")


class ChoiceCreateExamForm(FlaskForm):
    name = StringField("Question:", validators=[DataRequired(), Length(5, 30)])
    lang = SelectField(
        "Lang",
        default="py",
        choices=[("py", "python"), ("java", "java"), ("html", "html")],
    )
    exam_type = SelectField("Type", default="choice", choices=[("choice", "choice")])
    exam_level = SelectField(
        "Question Level:",
        choices=[
            ("Python Basics reg", "Python Basics reg"),
            ("Python Basics prem", "Python Basics prem"),
            ("Python Inter", "Python Inter"),
            ("Python Inter Prem", "Python Inter Prem"),
            ("Python adv", "Python adv"),
            ("Python adv prem", "Python adv prem"),
            ("HTML, CSS, JS reg", "HTML, CSS, JS reg"),
            ("HTML, CSS, JS prem", "HTML, CSS, JS prem"),
            ("Java Basics reg", "Java Basics reg"),
            ("Java Basics prem", "Java Basics prem"),
        ],
    )
    instruction = TextAreaField("Instruction")
    answer = TextAreaField("Answer")
    correct_answer = StringField("Correct Answer")
    submit = SubmitField("Create")

app/exam/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    SubmitField,
    HiddenField,
    TextAreaField,
    SelectField,
    BooleanField,
)
from wtforms.validators import DataRequired, Length


class ExamForm(FlaskForm):
    exam_id = HiddenField("id", validators=[DataRequired()])
    name = StringField("Question:", validators=[DataRequired(), Length(5, 30)])
    instruction = TextAreaField("Instruction")
    code = TextAreaField("Code")
    result = BooleanField("Result", default=False)
    submit = SubmitField("Submit")


class CreateExamForm(FlaskForm):
    name = StringField("Question:", validators=[DataRequired(), Length(5, 30)])
    lang = SelectField(
        "Lang",
        default="py",
        choices=[("py", "python"), ("java", "java"), ("html", "html")],
    )
    exam_type = SelectField("Type", default="code", choices=[("code", "code")])
    exam_level = SelectField(
        "Question Level:",
        choices=[
            ("Python Basics reg", "Python Basics Regular"),
            ("Python Basics prem", "Python Basics Premium"),
            ("Python Inter", "Python Intermediate"),
            ("Python Intermediate Premium", "Python Inter Prem"),
            ("Python adv", "Python Advanced"),
            ("Python adv prem", "Python Advanced Premium"),
            ("Java Basics reg", "Java Basics Regular"),
            ("Java Basics prem", "Java Basics Premium"),
            ("HTML, CSS, JS reg", "HTML, CSS, JS Regular"),
            ("HTML, CSS, JS prem", "HTML, CSS, JS Premium"),
        ],
    )
    instruction = TextAreaField("Instruction")
    solution = TextAreaField("Solution")
    template = TextAreaField("Template")
    verification = TextAreaField("Verification")
    submit = SubmitField("Create")


class SolutionForm(ExamForm):
    solution = TextAreaField("Solution")

app/exam/controller.py
import os
import subprocess
import tempfile
from flask import redirect, url_for
from .models import Exam
from app.logger import log


def check_answer(exam: Exam, code: str):
    """check exam result"""
    exam_lang = exam.lang.name
    MAP = {
        Exam.Language.py.name: check_answer_py,
        Exam.Language.java.name: check_answer_java,
        Exam.Language.js.name: check_answer_js,
    }
    if exam_lang not in MAP:
        log(log.ERROR, "unknown exam language: [%s]", exam_lang)
        return True
    return MAP[exam_lang](exam, code)


def check_answer_py(exam: Exam, code: str):
    with tempfile.TemporaryDirectory() as tmpdirname:
        test_file_path = os.path.join(tmpdirname, "test.py")
        with open(test_file_path, "w") as f:
            f.write(code)
            f.write("\n")
            if exam.verification:
                f.write("\n")
                f.write("\n")
                f.write(exam.verification)
                f.write("\n")
        cmd = ["python3", test_file_path]
        try:
            test_process = subprocess.run(cmd, capture_output=True, timeout=1)
            if test_process.stderr:
                for error_line in test_process.stderr.decode().split("\n"):
                    log(log.WARNING, "EXAM ERROR: %s", error_line)
                return False
            return test_process.returncode == 0
        except subprocess.TimeoutExpired:
            log(log.WARNING, "EXAM TIMEOUT: Exam:[%s]", exam.name)
            return False


def strip_code(source: str):
    target = [line[: line.find("//")] for line in source]
    target = [line.strip() for line in source]
    target = [line for line in target if line]
    return target


def check_answer_java(exam: Exam, code: str):
    solution_lines = strip_code(exam.solution)
    code_lines = strip_code(code)
    if len(solution_lines) != len(code_lines):
        return False
    for no_line in range(len(solution_lines)):
        if solution_lines[no_line] != code_lines[no_line]:
            return False

    return True


def check_answer_js(exam: Exam, code: str):
    return True


def check_answer_choice(exam_id: int, cor_index: str):
    correct_index = Exam.query.filter(Exam.id == exam_id).first()
    if correct_index.correct_answer == cor_index:
        return True


def prepare_goto_exam(the_exam, prev):
    exams = prepare_exams(the_exam=the_exam, reverse=prev)
    found_current = False
    next_exam = None
    index = 0
    for exam in exams:
        if found_current:
            next_exam = exam
            break
        if exam.id == the_exam.id:
            found_current = True
            if index >= (len(exams) - 1):
                first_exam = exams[0]
                next_exam = first_exam
                break
        index += 1

    return redirect(url_for(
        f"exam.exam_{the_exam.lang.name}",
        exam_id=next_exam.id)
        )


def goto_next_exam(exam):
    return prepare_goto_exam(
        the_exam=exam, prev=False)


def goto_prev_exam(exam):
    return prepare_goto_exam(
        the_exam=exam, prev=True)


def prepare_exams(the_exam, reverse):
    type_id = the_exam.type_id
    lang = the_exam.lang
    exams = (
        Exam.query.filter(Exam.lang == lang)
        .filter(Exam.type_id == type_id)
        .filter(Exam.deleted != True)  # noqa F712
        .all()
    )
    if reverse:
        exams.reverse()
    return exams


def next_exam_exists(the_exam):
    exams = prepare_exams(the_exam, reverse=False)
    return the_exam.id in [exam.id for exam in exams][0:-1]


def prev_exam_exists(the_exam):
    exams = prepare_exams(the_exam, reverse=True)
    return the_exam.id in [exam.id for exam in exams][0:-1]

app/exam/views.py
from flask import Blueprint, render_template, url_for, redirect, flash, request
from flask_user import roles_required, current_user

from .models import Exam, ExamLevel
from .forms import ExamForm, CreateExamForm, SolutionForm
from .choisen_answer.forms import ChoiceCreateExamForm, ChoiceExamForm
from .controller import (
    check_answer,
    goto_next_exam,
    check_answer_choice,
    goto_prev_exam,
    next_exam_exists,
    prev_exam_exists,
)
from app.result.controller import go_pass_exam, next_to_pass_exam, go_fail_exam
from app.tab import get_allowed_tabs
from app.logger import log

exam_blueprint = Blueprint("exam", __name__)


def render_base_template(template_name_or_list, **args):
    return render_template(template_name_or_list, tabs=get_allowed_tabs(), **args)


def exam_level_sort(reg_name: str, prem_name: str, path):
    level = ExamLevel.query.filter(ExamLevel.name == reg_name).first()
    exams = Exam.query.filter(Exam.type_id == level.id).all()
    level_prem = ExamLevel.query.filter(ExamLevel.name == prem_name).first()
    exams_prem = Exam.query.filter(Exam.type_id == level_prem.id).all()
    return render_base_template(path, exams=exams, exams_prem=exams_prem)


@exam_blueprint.route("/main_exam_py_base", methods=["GET", "POST"])
def main_exam_page_py_base():
    return exam_level_sort(
        "Python Basics reg", "Python Basics prem", "exam/main_exam_page_py_base.html"
    )


@exam_blueprint.route("/main_exam_py_inter", methods=["GET", "POST"])
def main_exam_page_py_inter():
    return exam_level_sort(
        "Python Inter", "Python Inter Prem", "exam/main_exam_page_py_inter.html"
    )


@exam_blueprint.route("/main_exam_py_adv", methods=["GET", "POST"])
def main_exam_page_py_adv():
    return exam_level_sort(
        "Python adv", "Python adv prem", "exam/main_exam_page_py_adv.html"
    )


@exam_blueprint.route("/main_exam_java", methods=["GET", "POST"])
def main_exam_page_java():
    return exam_level_sort(
        "Java Basics reg", "Java Basics prem", "exam/main_exam_page_java.html"
    )


@exam_blueprint.route("/main_exam_html", methods=["GET", "POST"])
def main_exam_page_html():
    return exam_level_sort(
        "HTML, CSS, JS reg", "HTML, CSS, JS prem", "exam/main_exam_page_html.html"
    )


@exam_blueprint.route("/exam/py/<exam_id>", methods=["GET", "POST"])
def exam_py(exam_id):
    exam = Exam.query.filter(Exam.id == exam_id).first()
    next_exam_exist = next_exam_exists(exam)
    prev_exam_exist = prev_exam_exists(exam)
    if exam.exam_type == Exam.Type.code:
        form = ExamForm(request.form)
    else:
        form = ChoiceExamForm(request.form)
        form.answer.choices = [(choice, choice) for choice in exam.answer.split("\n")]
    if form.validate_on_submit():
        if request.form["submit"] == "Next":
            user = current_user
            next_to_pass_exam(exam_id=exam.id, user_id=user.id)
            return goto_next_exam(exam=exam)
        elif request.form["submit"] == "Skip":
            return goto_next_exam(exam=exam)
        elif request.form["submit"] == "Prev":
            return goto_prev_exam(exam=exam)
        else:
            assert exam
            if exam.exam_type == Exam.Type.code:
                if check_answer(exam, form.code.data) is True:
                    flash(f"Question success '{exam.name}'.", "success")
                    user = current_user
                    go_pass_exam(exam_id=exam.id, user_id=user.id)
                else:
                    flash(f"Question failed '{exam.name}'.", "danger")
                    user = current_user
                    go_fail_exam(exam_id=exam.id, user_id=user.id)
            elif exam.exam_type == Exam.Type.choice:
                if check_answer_choice(exam.id, form.answer.data) is True:
                    flash(f"Question success '{exam.name}'.", "success")
                    user = current_user
                    go_pass_exam(exam_id=exam.id, user_id=user.id)
                else:
                    flash(f"Question failed '{exam.name}'.", "danger")
                    user = current_user
                    go_fail_exam(exam_id=exam.id, user_id=user.id)
            else:
                flash(f"Question failed '{exam.name}'.", "danger")
                user = current_user
                go_fail_exam(exam_id=exam.id, user_id=user.id)
            if exam.exam_type == Exam.Type.code:
                return render_base_template(
                    "exam/exam.html",
                    form=form,
                    instruction_height=(exam.instruction.count("\n") + 2),
                    code_height=(exam.template.count("\n") + 2),
                    next_exam_exist=next_exam_exist,
                    prev_exam_exist=prev_exam_exist,
                )
            elif exam.exam_type == Exam.Type.choice:
                return render_base_template(
                    "exam/exam_choice.html",
                    form=form,
                    instruction_height=(exam.instruction.count("\n") + 2),
                    next_exam_exist=next_exam_exist,
                    prev_exam_exist=prev_exam_exist,
                )
            else:
                return render_base_template(
                    "exam/exam.html",
                    form=form,
                    instruction_height=(exam.instruction.count("\n") + 2),
                    code_height=(exam.template.count("\n") + 2),
                    next_exam_exist=next_exam_exist,
                    prev_exam_exist=prev_exam_exist,
                )
    elif form.is_submitted():
        if request.form["submit"] == "Next":
            user = current_user
            next_to_pass_exam(exam_id=exam.id, user_id=user.id)
            return goto_next_exam(exam=exam)
        elif request.form["submit"] == "Prev":
            return goto_prev_exam(exam=exam)
        elif request.form["submit"] == "Skip":
            return goto_next_exam(exam=exam)
        else:
            flash("Need an answer", "danger")

    if exam.exam_type == Exam.Type.code:
        form.name.data = exam.name
        form.exam_id.data = exam.id
        form.code.data = exam.template
        form.instruction.data = exam.instruction
        return render_base_template(
            "exam/exam.html",
            form=form,
            instruction_height=(exam.instruction.count("\n") + 2),
            next_exam_exist=next_exam_exist,
            prev_exam_exist=prev_exam_exist,
        )
    form.name.data = exam.name
    form.exam_id.data = exam.id
    form.answer.choices = [(choice, choice) for choice in exam.answer.split("\n")]
    form.instruction.data = exam.instruction
    return render_base_template(
        "exam/exam_choice.html",
        form=form,
        instruction_height=(exam.instruction.count("\n") + 2),
        next_exam_exist=next_exam_exist,
        prev_exam_exist=prev_exam_exist,
    )


@exam_blueprint.route("/exam_lang/<lang>")
def exam_lang(lang):
    exam = Exam.query.filter(Exam.lang == lang).first()
    return redirect(url_for(f"exam.exam_{lang}", exam_id=exam.id))


@exam_blueprint.route("/exam/java/<exam_id>", methods=["GET", "POST"])
def exam_java(exam_id):
    exam = Exam.query.filter(Exam.id == exam_id).first()
    next_exam_exist = next_exam_exists(exam)
    prev_exam_exist = prev_exam_exists(exam)
    if exam.exam_type == Exam.Type.code:
        form = ExamForm(request.form)
    else:
        form = ChoiceExamForm(request.form)
        form.answer.choices = [(choice, choice) for choice in exam.answer.split("\n")]
    if form.validate_on_submit():
        if request.form["submit"] == "Next":
            user = current_user
            next_to_pass_exam(exam_id=exam.id, user_id=user.id)
            return goto_next_exam(exam=exam)
        elif request.form["submit"] == "Prev":
            return goto_prev_exam(exam=exam)
        elif request.form["submit"] == "Skip":
            return goto_next_exam(exam=exam)
        else:
            assert exam
            if exam.exam_type == Exam.Type.code:
                if check_answer(exam, form.code.data):
                    flash(f"Question success '{exam.name}'.", "success")
                    user = current_user
                    go_pass_exam(exam_id=exam.id, user_id=user.id)
                else:
                    flash(f"Question failed '{exam.name}'.", "danger")
                    user = current_user
                    go_fail_exam(exam_id=exam.id, user_id=user.id)
            elif exam.exam_type == Exam.Type.choice:
                if form.answer.data is None:
                    flash("Need an answer", "danger")
                if check_answer_choice(exam.id, form.answer.data):
                    flash(f"Question success '{exam.name}'.", "success")
                    user = current_user
                    go_pass_exam(exam_id=exam.id, user_id=user.id)
                else:
                    flash(f"Question failed '{exam.name}'.", "danger")
                    user = current_user
                    go_fail_exam(exam_id=exam.id, user_id=user.id)
            else:
                flash(f"Question failed '{exam.name}'.", "danger")
            # return redirect(url_for("exam.exam_py", exam_id=exam_id))
            if exam.exam_type == Exam.Type.code:
                return render_base_template(
                    "exam/exam.html",
                    form=form,
                    instruction_height=(exam.instruction.count("\n") + 2),
                    code_height=(exam.template.count("\n") + 2),
                    next_exam_exist=next_exam_exist,
                    prev_exam_exist=prev_exam_exist,
                )
            elif exam.exam_type == Exam.Type.choice:
                return render_base_template(
                    "exam/exam_choice.html",
                    form=form,
                    instruction_height=(exam.instruction.count("\n") + 2),
                    next_exam_exist=next_exam_exist,

app/templates/exam/create_exam_choice.html
{% extends 'base.html' %}

{% block scripts %}
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>


{% endblock %}

{% block content %}
<div class="container py-4">
    <form class="form" role="form" action="{{ post_action }}" method="post">
        <div class="form-group">
            {{form.name.label}}
            {{form.name(class='form-control')}}
        </div>
        <div class="form-group">
            {{form.lang.label}}
            {{form.lang(class='form-control')}}
        </div>
        <div class="form-group">
            {{form.exam_type.label}}
            {{form.exam_type(class='form-control')}}
        </div>
        <div class="form-group">
            {{form.exam_level.label}}
            {{form.exam_level(class='form-control')}}
        </div>
        <div class="form-group">
            {{form.instruction.label}}
            {{form.instruction(class='form-control', rows=5)}}
        </div>
        <div class="form-group">
            {{form.answer.label}}
            {{form.answer(class='form-control')}}
        </div>
        <div class="form-group">
            {{form.correct_answer.label}}
            {{form.correct_answer(class='form-control',  rows=1)}}
        </div>
        <div style="margin-top: 1%;">
            {{form.submit(class='btn btn-primary', value="Create")}}
        </div>
    </form>
</div>


{% endblock %}

app/templates/exam/create_exam_py.html
{% extends 'base.html' %}

{% block content %}
<div class="container py-4">
    <form class="form" role="form" action="{{ post_action }}" method="post">
        <div class="form-group">
            {{form.name.label}}
            {{form.name(class='form-control')}}
        </div>
        <div class="form-group">
            {{form.lang.label}}
            {{form.lang(class='form-control')}}
        </div>
        <div class="form-group">
            {{form.exam_type.label}}
            {{form.exam_type(class='form-control')}}
        </div>
        <div class="form-group">
            {{form.exam_level.label}}
            {{form.exam_level(class='form-control')}}
        </div>
        <div class="form-group">
            {{form.instruction.label}}
            {{form.instruction(class='form-control', rows=5)}}
        </div>
        <div class="form-group">
            {{form.solution.label}}
            {{form.solution(class='form-control', rows=5, id="code")}}
        </div>
        <div class="form-group">
            {{form.template.label}}
            {{form.template(class='form-control', rows=3)}}
        </div>
        <div class="form-group">
            {{form.verification.label}}
            {{form.verification(class='form-control', rows=3)}}
            {% for error in form.errors.code %}
            <small class="text-danger">{{error}}</small>
            {% endfor %}
        </div>
        <div style="margin-top: 1%;">
            {{form.submit(class='btn btn-primary', value="Create")}}
        </div>
    </form>
</div>
{% endblock %}

app/templates/exam/exam.html
{% extends 'base.html' %}

{% block content %}
<div class="container py-4">
  <form class="form" role="form" action="{{ url_for('exam.exam_py', exam_id=form.exam_id.data) }}" method="post">
    {{form.exam_id}}
    {% if current_user.is_exam_passed(form.exam_id.data) %}
    {{form.name(class='form-control is-valid', readonly=True)}}
    {% else %}
    {{form.name(class='form-control', readonly=True)}}
    {% endif %}
    <!-- </div> -->
    <div class="form-group">
      {{form.instruction(class='form-control', readonly=True, rows=instruction_height)}}
    </div>
    <div class="form-group">
      {{form.code.label}}
      {{form.code(class='form-control', rows=6)}}
      {% for error in form.errors.code %}
      <small class="text-danger">{{error}}</small>
      {% endfor %}
    </div>
    {% if prev_exam_exist %}
    <button class="btn btn-primary " type="submit" name="submit" value="Prev">&lt;&lt;Back</button>
    {% else %}
    <div>Beginning of questions</div>
    {% endif %}
    <button class="btn btn-primary " type="submit" name="submit" value="Go">Submit</button>
    <a class="btn btn-primary" href="{{ url_for('exam.show_solution', exam_id=form.exam_id.data)}}">See answer</a>
    {% if next_exam_exist %}
    <button class="btn btn-primary " type="submit" name="submit" value="Next">Next&gt;&gt;</button>
    <button class="btn btn-primary " type="submit" name="submit" value="Skip">Skip question&gt;&gt;</button>
    {% else %}
    <div>End of questions</div>
    {% endif %}
  </form>
</div>
{% endblock %}

app/templates/exam/exam_choice.html
{% extends 'base.html' %}

{% block content %}
<div class="container py-4">
    <form class="form" role="form" action="{{ url_for('exam.exam_py', exam_id=form.exam_id.data) }}" method="post">
        {{form.exam_id}}
        {% if current_user.is_exam_passed(form.exam_id.data) %}
        {{form.name(class='form-control is-valid', readonly=True)}}
        {% else %}
        {{form.name(class='form-control', readonly=True)}}
        {% endif %}
        <!-- </div> -->
        <div class="form-group">
            {{form.instruction(class='form-control', readonly=True, rows=instruction_height)}}
        </div>
        <table class="radio">
            {% for subfield in form.answer %}
            <tr>
                <td>{{ subfield }}</td>
                <td>{{ subfield.label }}</td>
            </tr>
            {% endfor %}
        </table>
        <div style="margin-top: 5%;">
            {% if prev_exam_exist %}
            <button class="btn btn-primary " type="submit" name="submit" value="Prev">&lt;&lt;Back</button>
            {% else %}
            <div>Beginning of questions</div>
            {% endif %}
            <button class="btn btn-primary " type="submit" name="submit" value="Go">Submit</button>
            <a class="btn btn-primary" href="{{ url_for('exam.show_solution', exam_id=form.exam_id.data)}}">See answer</a>
            {% if next_exam_exist %}
            <button class="btn btn-primary " type="submit" name="submit" value="Next">Next&gt;&gt;</button>
            <button class="btn btn-primary " type="submit" name="submit" value="Skip">Skip question&gt;&gt;</button>
            {% else %}
            <div>End of questions</div>
            {% endif %}
        </div>
    </form>
</div>
{% endblock %}

app/templates/exam/exam_choise.html
{% extends 'base.html' %}

{% block content %}
<div class="container py-4">
    <form class="form" role="form" action="{{ url_for('exam.exam_py', exam_id=form.exam_id.data) }}" method="post">
        {{form.exam_id}}
        {% if current_user.is_exam_passed(form.exam_id.data) %}
        {{form.name(class='form-control is-valid', readonly=True)}}
        {% else %}
        {{form.name(class='form-control', readonly=True)}}
        {% endif %}
        <!-- </div> -->
        <div class="form-group">
            {{form.instruction(class='form-control', readonly=True, rows=instruction_height)}}
        </div>
        <table class="radio">
            {% for subfield in form.answer %}
            <tr>
                <td>{{ subfield }}</td>
                <td>{{ subfield.label }}</td>
            </tr>
            {% endfor %}
        </table>
        <div style="margin-top: 5%;">
            <button class="btn btn-primary " type="submit" name="submit" value="Prev">&lt;&lt;Back</button>
            <button class="btn btn-primary " type="submit" name="submit" value="Go">Go</button>
            <button class="btn btn-primary " type="submit" name="submit" value="Next">Next&gt;&gt;</button>
        </div>
    </form>
</div>
{% endblock %}

app/templates/exam/main_exam_page_java.html
{% extends 'base.html' %}

{% block content %}
<link rel="stylesheet" href="/static/css/jquery.dataTables.min.css">
{% if current_user.roles[0].name == "Admin"
or current_user.roles[0].name == "Student_J_reg"
or current_user.roles[0].name == "Student_J_pre"
or current_user.roles[0].name == "Student_J_pre_outsider"
 %}
<table style="margin-top: 2%; margin-left: 5%;" cellspacing="0" width="50%">
    <thead>
        <tr>
            <th scope="col">Question Java</th>
        </tr>
    </thead>
    <tbody style="margin-top: 5%;">
        {% for exam in exams %}
        <tr>
            <td>
                {%set exam_passed = current_user.is_exam_passed(exam.id)%}
                    {% if exam_passed is boolean %}
                    {% if exam_passed %}
                    &#9989;
                    {% else %}
                    &#10060;
                    {% endif %}
                    {% endif %}
                <a href="{{ url_for('exam.exam_py', exam_id=exam.id) }}">

                    {{exam.name}}</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}
{% if current_user.roles[0].name == "Admin"
or current_user.roles[0].name == "Student_J_pre"
or current_user.roles[0].name == "Student_J_pre_outsider" %}
<table style="margin-top: 2%; margin-left: 5%;" cellspacing="0" width="50%">
    <thead>
        <tr>
            <th scope="col">Question Java Prem</th>
        </tr>
    </thead>
    <tbody style="margin-top: 5%;">
        {% for exam in exams_prem %}
        <tr>
            <td>
                {%set exam_passed = current_user.is_exam_passed(exam.id)%}
                    {% if exam_passed is boolean %}
                    {% if exam_passed %}
                    &#9989;
                    {% else %}
                    &#10060;
                    {% endif %}
                    {% endif %}
                <a href="{{ url_for('exam.exam_java', exam_id=exam.id) }}">
                    {{exam.name}}</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}
{% endblock %}

app/templates/exam/show_solution.html
{% extends 'base.html' %}

{% block content %}
<div class="container py-4">
    <form class="form" role="form" action="{{ url_for('exam.exam_py', exam_id=form.exam_id.data) }}" method="post">
        {{form.exam_id}}
        {{form.name(class='form-control', readonly=True)}}
        <!-- </div> -->
        <div class="form-group">
            {{form.instruction(class='form-control', readonly=True, rows=instruction_height)}}
        </div>
        {% if not form.correct_answer  %}
        <div class="form-group">
            {{form.code.label}}
            {{form.code(class='form-control', rows=code_height)}}
            {% for error in form.errors.code %}
            <small class="text-danger">{{error}}</small>
            {% endfor %}
        </div>
        <div class="form-group">
            {{form.solution.label}}
            {{form.solution(class='form-control', readonly=True, rows=10)}}
        </div>
        {% endif  %}
        {% if form.correct_answer  %}
        <div class="form-group">
            <div>Correct answer</div>
            <div>{{form.correct_answer}}</div>
            
        </div>
        {% endif  %}
        <button class="btn btn-primary " type="submit" name="submit" value="Prev">&lt;&lt;Back</button>
        <button class="btn btn-primary " type="submit" name="submit" value="Go">Submit</button>
        <a class="btn btn-primary" href="{{ url_for('exam.exam_py', exam_id=form.exam_id.data) }}">Hide
            Solution</a>
        <button class="btn btn-primary " type="submit" name="submit" value="Next">Next&gt;&gt;</button>
    </form>
</div>
{% endblock %}